### ISSUE TITLE
.Net Standard support

### ISSUE THREAD

**Issue by petriashev** [phatboyg/GreenPipes#18]
.Net Standard support
found develop-netcore branch but no nuget package

**Comment by phatboyg** [comment]
Yeah, there is no package yet because the build system is whack. Once the project stuff ships it will happen for sure.

**Comment by andymac4182** [comment]
Any update on this?

**Comment by phatboyg** [comment]
It will happen, at some point.

**Comment by andymac4182** [comment]
https://github.com/MassTransit/GreenPipes/pull/3 @petriashev this is the first step

**Comment by phatboyg** [comment]
It's already done.
