### ISSUE TITLE
BasePipeContext.AddOrUpdatePayload - Update callback adds new element to context instead of updating

### ISSUE THREAD

**Issue by pawepaw** [phatboyg/GreenPipes#22]
Hi,

I was investigating some issue and i've found that update callback in BasePipeContext.AddOrUpdatePayload https://github.com/phatboyg/GreenPipes/blob/7be9ab13dc3ac40e53fe9a2ac330e2bb20ff4c75/src/GreenPipes/Payloads/PayloadCache.cs#L93 always adds new element to context instead of updating it. Basically it does exactly the same as add. 
```
                    if (_collection.TryGetPayload(out T existingValue))
                    {
                        if (context == null || previousValue != existingValue)
                            context = new PayloadValue<T>(updateFactory(existingValue));

                        previousValue = existingValue;

                        currentCollection = Volatile.Read(ref _collection);

                        Interlocked.CompareExchange(ref _collection, currentCollection.Add(context), currentCollection);
                    }
```
Is there any way to update existing value in context? Or is it maybe guaranteed that only newest added element is returned? So even though there is old object and new produced by update factory in context it will always return new one?

**Comment by phatboyg** [comment]
The newest element is always returned. The check for a payload type works in reverse, from the tail to the head, so adding a new entry is the safest way to get a value updated. Particularly since a scope may be active, and the updated value shouldn't update the one outside of the scope.

**Comment by pawepaw** [comment]
ok so basically even though there are more objects and previous are considered "obsolete" the newly added is always returned.
