### ISSUE TITLE
Is it possible to do logs before next task processing and in case of an exception of next task processing?

### ISSUE THREAD

**Issue by roman-ianchenko** [phatboyg/GreenPipes#26]
https://github.com/phatboyg/GreenPipes/blob/7be9ab13dc3ac40e53fe9a2ac330e2bb20ff4c75/src/GreenPipes/Filters/LogFilter.cs#L41

Is it made intentionally, to pass the whole TextWriter object to use only one its method. What if my log implementation is not inherited from TextWriter?

**Comment by phatboyg** [comment]
The filters included are examples, you are welcome to create your own to suit your needs.

**Comment by roman-ianchenko** [comment]
Ok, thank you, will try.

**Comment by roman-ianchenko** [comment]
Could you please check this PR https://github.com/phatboyg/GreenPipes/pull/27 and add this change to next version of MassTransit package.

**Comment by phatboyg** [comment]
Thanks, for bringing this up.
