### ISSUE TITLE
Issue with v3 Greenpipes.Payloads.PayloadCache 

### ISSUE THREAD

**Issue by Karthickeyanofficial** [phatboyg/GreenPipes#30]
I used the Greenpipes v 3.0.0 with the 
automatonymous v 4.2.0 
masstransit as 5.5.6 
masstransit.automatonymous as v 5.5.5

i received following error

Could not load type 'GreenPipes.Payloads.PayloadCache' from assembly 'GreenPipes, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b800c4cfcdeea87b'.

Could you please let us know how to resolve this one?

**Comment by phatboyg** [comment]
Don't upgrade past the required version for that version of MassTransit, which is 2.1.4.

https://www.nuget.org/packages/MassTransit/5.5.6
